[package]
name = "code-seek"
version = "0.4.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
toml = "1"
tree-sitter = "0.25"
tree-sitter-c = "0.24"
tree-sitter-cpp = "0.23"
tree-sitter-qmljs = "0.3"
tree-sitter-rust = "0.24"

[dev-dependencies]
tree-sitter = "0.25"
